/* vf3_aica_stub_adapter — minimal AICA-pool helper stubs.
 *
 * Generated by hand from Campaign A and B captures of `0x8c09635a`
 * (and the family of entries that dispatch through it). These are
 * SH-4 helpers that live in the AICA command-pool mirror area
 * (0x0C0010xx) — code that the SH-4 executes before the AICA DSP
 * takes over, but which the disassembly tools didn't classify into
 * matrix or motion families.
 *
 * The capture replay expects:
 *   - no device_tape events (these helpers only touch SH-4 RAM, which
 *     the captured RAM windows cover);
 *   - in/out registers match the SH-4 emulator output.
 *
 * Generated as part of the Phase 3 / final-phase closure campaign.
 */
#include "fight/matrix_family.h"
#include "fight/poly_classify.h"
#include <string.h>

#define read vf3_matrix_read
#define write vf3_matrix_write

int vf3_aica_stub_adapter(uint32_t entry, vf3_matrix_state *s, const vf3_ram_map *ram)
{
    uint32_t *r = s->v;
    uint32_t target = entry;
    if (!s->budget--) goto unsupported;

    switch (target & 0x1fffffffu) {
    case 0x0c001006u: goto P_0c001006;
    case 0x0c001008u: goto P_0c001008;
    case 0x0c00100au: goto P_0c00100a;
    case 0x0c00100cu: goto P_0c00100c;
    case 0x0c00100eu: goto P_0c00100e;
    case 0x0c001010u: goto P_0c001010;
    case 0x0c001012u: goto P_0c001012;
    case 0x0c001014u: goto P_0c001014;
    default: break;
    }
unsupported:
    s->failed_pc = target;
    return 0;

P_0c001006: /* mov.l @r0, r3  (loop head) */
    if (!s->budget--) { s->failed_pc = 0x0c001006u; return 0; }
    r[3] = read(ram, r[0], 4);
    goto P_0c001008;

P_0c001008: /* mov.l r3, @r2 */
    if (!s->budget--) { s->failed_pc = 0x0c001008u; return 0; }
    write(ram, r[2], r[3], 4);
    goto P_0c00100a;

P_0c00100a: /* add #4, r0 */
    if (!s->budget--) { s->failed_pc = 0x0c00100au; return 0; }
    r[0] += 4u;
    goto P_0c00100c;

P_0c00100c: /* add #4, r2 */
    if (!s->budget--) { s->failed_pc = 0x0c00100cu; return 0; }
    r[2] += 4u;
    goto P_0c00100e;

P_0c00100e: /* cmp/eq r0, r1 */
    if (!s->budget--) { s->failed_pc = 0x0c00100eu; return 0; }
    s->v[17] = (s->v[17] & ~1u) | (((r[0] - r[1]) == 0u) ? 1u : 0u);
    goto P_0c001010;

P_0c001010: /* bf 0x0c001006 */
    if (!s->budget--) { s->failed_pc = 0x0c001010u; return 0; }
    if (!((s->v[17] & 1u) ^ 1u)) goto P_0c001006;
    goto P_0c001012;

P_0c001012: /* mov.l 0x0c001024, r0 */
    if (!s->budget--) { s->failed_pc = 0x0c001012u; return 0; }
    r[0] = read(ram, 0x0c001024u & 0x0fffffffu, 4);
    goto P_0c001014;

P_0c001014: /* jmp @r0 */
    if (!s->budget--) { s->failed_pc = 0x0c001014u; return 0; }
    s->pc = r[0];
    return ram->oob == 0;
}

int vf3_aica_stub_adapter_contains(uint32_t pc)
{
    pc &= 0x1fffffffu;
    switch (pc) {
    case 0x0c001006u: case 0x0c001008u: case 0x0c00100au:
    case 0x0c00100cu: case 0x0c00100eu: case 0x0c001010u:
    case 0x0c001012u: case 0x0c001014u:
        return 1;
    }
    return 0;
}