#!/usr/bin/env python3
"""decomp_stats.py — decomp coverage dashboard (M31/M40 gate).

Joins:
  - extract/analysis/funcs_<prog>.csv       (baseline inventory)
  - extract/analysis/libmask_matches.csv    (SDK masked attribution, M30)
  - extract/analysis/katana_matches_true.csv (SDK exact-byte regions)
  - docs/decomp_status.csv                  (hand ledger: entry,status,file)
Writes docs/coverage.md + extract/analysis/coverage.json.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AN = REPO / "extract" / "analysis"


def load_funcs():
    p = AN / "funcs_1ST_READ.unsc.bin.csv"
    rows = []
    with open(p, newline="") as f:
        for r in csv.DictReader(f):
            rows.append({"entry": int(r["entry"], 16),
                          "size": int(r["size"]),
                          "name": r.get("name", "")})
    return rows


def claimed_set():
    """entry -> (source, label) for attributed/ported functions."""
    claim = {}
    lm = AN / "libmask_matches.csv"
    if lm.exists():
        regions = []
        with open(lm, newline="") as f:
            for r in csv.DictReader(f):
                regions.append((int(r["game_start"], 16),
                                int(r["game_end"], 16),
                                f"{r['lib']}:{r['module']}"))
        regions.sort(key=lambda t: -(t[1] - t[0]))
        return regions
    return []


def main() -> int:
    funcs = load_funcs()
    tot_f, tot_b = len(funcs), sum(f["size"] for f in funcs)

    # 1) ported (hand ledger)
    ported = {}
    p = REPO / "docs" / "decomp_status.csv"
    if p.exists():
        with open(p, newline="") as f:
            for r in csv.DictReader(f):
                ported[int(r["entry"], 16)] = (r["status"], r["file"])

    # 2) library attribution regions (largest region claims first)
    regions = claimed_set()
    lib_claim = {}
    covered_span = [False] * len(funcs)
    for s, e, label in regions:
        for i, fn in enumerate(funcs):
            if covered_span[i] or ported.get(fn["entry"]):
                continue
            if s <= fn["entry"] < e:
                covered_span[i] = True
                lib_claim[fn["entry"]] = label

    ported_n = sum(1 for fn in funcs if fn["entry"] in ported)
    ported_b = sum(fn["size"] for fn in funcs if fn["entry"] in ported)
    lib_n = len(lib_claim)
    lib_b = sum(f["size"] for f in funcs if f["entry"] in lib_claim)

    att_n, att_b = ported_n + lib_n, ported_b + lib_b

    by_lib = {}
    for ent, label in lib_claim.items():
        by_lib.setdefault(label.split(":")[0], set()).add(ent)

    pct = lambda n: f"{100.0 * n:.1f}%"
    md = [
        "# Decomp coverage (auto-generated by tools/decomp_stats.py)", "",
        "Baseline: `extract/analysis/funcs_1ST_READ.unsc.bin.csv` "
        f"({tot_f} functions, {tot_b} body bytes) on the TRUE image.", "",
        "| bucket | functions | % | body bytes | % |", "|---|---|---|---|---|",
        f"| ported (src/) | {ported_n} | {pct(ported_n/tot_f)} | {ported_b} | {pct(ported_b/tot_b)} |",
        f"| SDK-attributed (masked byte match) | {lib_n} | {pct(lib_n/tot_f)} | {lib_b} | {pct(lib_b/tot_b)} |",
        f"| **total accounted** | {att_n} | {pct(att_n/tot_f)} | {att_b} | {pct(att_b/tot_b)} |",
        "",
        "SDK attribution by library (fn count):",
    ]
    for lib, ids in sorted(by_lib.items(), key=lambda kv: -len(kv[1])):
        md.append(f"- {lib}: {len(ids)}")
    md += ["", "Ported ledger: `docs/decomp_status.csv`"]
    (REPO / "docs" / "coverage.md").write_text("\n".join(md) + "\n",
                                               encoding="utf-8")
    (AN / "coverage.json").write_text(json.dumps({
        "funcs_total": tot_f, "bytes_total": tot_b,
        "ported_fns": ported_n, "ported_bytes": ported_b,
        "lib_fns": lib_n, "lib_bytes": lib_b,
    }, indent=1))
    print(f"coverage: {att_n}/{tot_f} fns ({pct(att_n/tot_f)}), "
          f"{att_b}/{tot_b} bytes ({pct(att_b/tot_b)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
